### ISSUE TITLE
Tev cannot open images on SMB network drive on Windows 10

### ISSUE THREAD

**Issue by MKimiSH** [Tom94/tev#105]
Recently, I attempted to open an EXR image located on an SMB network drive using Tev. It failed to open the image, with error message `File <filename> could not be opened`. 

I think this could be due to the double backslashes in the front of SMB-mapped filenames, like `\\<remote>\<folder>\<image>.exr`. I suspect this is the reason, because in the error message, the double backslashes are stripped, leaving only `File <remote>\<folder>\<image>.exr could not be opened`. 

For comparison, Tev can read the same image successfully on MacOS (Catalina), and can also read an image mapped with SSHFS-Win (whose path starts with `Y:\` instead of `\\`) on the same Windows machine. 

I don't know how to make this issue reproducible, but it sounds very specific and I hope there is an easy fix. 

Thanks!

**Comment by Tom94** [comment]
Sorry for the delay; I didn't really feel like dealing with Windows' path craziness until now. :p

Please let me know if there's a corner case that I missed and still breaks.

**Comment by MKimiSH** [comment]
Hi Thomas,

Thanks so much! I really didn't expect Windows path handling to be so messy. In my case the updated version works perfectly.
