### ISSUE TITLE
Wrong binary in release package?

### ISSUE THREAD

**Issue by JiayinCao** [Tom94/tev#114]
Hi,

I noticed that the pre-compiled binaries ( both Mac and Windows ) try listening to the port through UDP, instead of TCP.
Since you mentioned in the other bug that TEV used to use UDP before, is there any chance that precompiled binary is an mismatched version with the release version?

Thanks

**Comment by JiayinCao** [comment]
Below is a screen shot that I take from my Windows that reveals TEV listens to the port through UDP
![image](https://user-images.githubusercontent.com/5715405/107857948-53c11300-6de6-11eb-8c5f-86e410d68af1.png)

If I build from source code, it works as expected through TCP.

**Comment by Tom94** [comment]
Yup, it's been a while since I last generated a binary release. (It's not fully automatic.)

I created a new one that has all the latest bells and whistles: https://github.com/Tom94/tev/releases/tag/v1.17
