### ISSUE TITLE
IPC docs

### ISSUE THREAD

**Issue by KarelPeeters** [Tom94/tev#116]
First of all thanks for writing this tool, it very quick and easy to use!

I read that tev supports some kind of IPC protocol where it can show an image while it is being rendered. From what I gather you're supposed to send the image data to tev using TCP on the port it prints when it starts up, and the port is also configurable from the commandline options, that all makes sense.

What I can't find anywhere is what exactly I'm supposed to send to tev. Do I just dump the content of an exr file in a single TCP packet? Or is there some kind of custom protocol for sending incremental updates to tev?

Maybe instructions for this could be added to the README? I could be missing something but I can't find any documentation about the IPC feature.

**Comment by Tom94** [comment]
Hi there (and sorry for the delay),

you're right in that there's no documentation on IPC (yet). I don't really know when I'll find the time to draft one up, so let me give you a quick summary.

- IPC uses a custom protocol over TCP.
- Each packet has the form `[uint32_t total_length_in_bytes][char type][char[] payload]`
- Every integer is little endian. (This is not yet enforced when compiling tev for big-endian systems, so expect breakage until I get around fixing it.)
- There are helper functions in [Ipc.cpp](https://github.com/Tom94/tev/blob/master/src/Ipc.cpp) (`IpcPacket::set*`) that show you exactly how each packet has to be assembled. Should be self-explanatory. If you want, you can just copy and paste them into your project.

The following kinds of operations are supported:

**OpenImage** - Opens an image from a specified path. This is used internally by tev and probably uninteresting to you.
**CreateImage** - Create a blank image with a specified size and a specified set of channel names ("R", "G", "B" [, "A"] is what you should use if you're rendering an image.)
**UpdateImage** - Lets you send updated pixel values to a specified image region and a specified set of channels
**CloseImage** - Does what you expect.
**ReloadImage** - likewise.

Hope this helps and lmk if anything is unclear!

**Comment by KarelPeeters** [comment]
Thanks a lot for the reply! Your summary was anough for me to get a working implementation together. I'm writing something in Rust so it's a bit difficult to just include the tev headers, I might actually write a full crate for this and publish it.

There are a few issues I encountered while experimenting around:

* Paths don't appear to work correctly (on Windows), when I send an `OpenImage` command with path `C:\Documents\test.exr`  it tries to open the file `C:\Install\C:\Documents\test.exr` instead, where `tev.exe` is located in `C:\Install`. I think the problem is that tev wants to split the string at `:` for tha channel selectors and gets confused. I'm not sure what the best solution here is, but right now it's basically impossible to open paths on windows as far as I can tell.

* When you create a new image with a name that already exists a new image is indeed created but `UpdateImage` commands are still applied to the earlier image, which is kind of annoying when the resolution changes or you want to start a new renderer. Maybe it would be better if each newly created image got a unique ID that's sent back over TCP to the client application and then that ID could be used instead of the name for future commands? That would require creating new versions of at least `UpdateImage` and `CloseImage` though.

* It's possible to segfault tev when strings are not properly 0-terminated or overrun the buffer, [`IStream& operator>>(std::string& var)`](https://github.com/Tom94/tev/blob/bafae16f9ab09fc75f9c4ae91e82066c1144070e/include/tev/Ipc.h#L119-L126) does not check the buffer while the other `>>` methods do.

* When the actual packet length is larger than the length stated at the start of the packet the error printed is 
  > Trying to read beyond the bounds of the IPC packet payload.

  This really confused me and it took me a while to realize that I forgot to include the 4 extra bytes for the length in the length itself as well. The `IStream` constructor tries to generate a user-readable error message [here](https://github.com/Tom94/tev/blob/bafae16f9ab09fc75f9c4ae91e82066c1144070e/include/tev/Ipc.h#L101-L107), but at that point it's too late since the [TCP receiving code](https://github.com/Tom94/tev/blob/bafae16f9ab09fc75f9c4ae91e82066c1144070e/src/Ipc.cpp#L537-L552) already forces the length to be correct. It _should_ be possible to do better than this, since TCP also knows the correct length and the code could check against that.

If you're interested I can submit PR for some of this stuff, none of it is too hard to fix but I want to know what you think first.

**Comment by Tom94** [comment]
Heya, thanks for going through these! No need to create a PR --- I quickly fixed the easy ones myself.

Regarding the other points:
- __Unique identifiers__: I'd like to avoid having bidirectional IPC communication. A fire-and-forget approach is much easier to maintain. That said, you can already do unique identifiers: just give each new image that you create a new unique name. Or, if you want to keep the same name, close the previously created image first. (I can't think of a good reason to create multiple images with the same name but different content.)
- __Obtaining packet length from TCP__: While this is theoretically possible, I do quite like the current approach in that it places fewer requirements on the underlying protocol: it does not assume atomicity of the packets. I don't think it's worth dropping that flexibility just for a nicer error message. Happy to be convinced otherwise, though, in case I'm missing another argument. :)

**Comment by KarelPeeters** [comment]
Allright, that was quick, thanks for the fixes!

The project stopped compiling for me though, now I get this cmake error: https://gist.github.com/KarelPeeters/a57be9409be15b908065ea669fed0921. It looks like #118 broke the build, since 4b3d95ed is the first commit that doesn't compile. Unfortunately I know very little about CMake so I have no idea what's going wrong.

I don't have a very strong opinion on the unique IDs, it was just a thought I had. But you're right, changing into a bidirectional protocol would be a significant step up in complexity. I guess I'll survive with generating my own unique names!

I thought the known-packet length stuff was the main purpose of the UDP to TCP switch but after some more reading it turns out I had my networking protocols a bit mixed up. Still, it's hard to imagine ever switching away from TCP to some other protocol that does not have atomic packets so I don't really see the downside of adding a quick check.

**Comment by Tom94** [comment]
The compilation error means that you didn't fetch the newly added submodule. tev has a helper script to deal with this kind of stuff if you don't wanna git it yourself: `scripts/pull.sh`.

**Comment by KarelPeeters** [comment]
Ah right, git submodules are always fun. I even needed to do `git submodule init` before the update commands.

Unfortunatly I think https://github.com/Tom94/tev/blob/ddc7ab04b2ec6ae7f010430c182803eaf475807c/include/tev/Ipc.h#L134 is a mistake, because `bool` and `std::string` have their own `<<` and `>>` overloads their effective sizes aren't neccesarily the same as the size of `T`. Right now strings in packets are impossible to send, and in theory booleans could be broken too because their size is not guaranteed to be `1`.

**Comment by KarelPeeters** [comment]
FYI I finished implementing the Rust wrapper around the API, it wasn't that much work: https://crates.io/crates/tev_client

**Comment by Tom94** [comment]
Good catch, thank you! (Fixed.)

Also, thanks for creating the Rust wrapper so quickly. I'll leave this issue open so when I get around writing docs for IPC I remember to reference it.

**Comment by tomasiser** [comment]
If anyone was interested, I also made a simple Python tev/IPC wrapper some time ago!

Example usage:
```python
with TevIpc() as tev:
    image_data = np.full((100,100,3), 1.0)
    image_data[40:61,:,0] = 0.0
    image_data[:,40:61,1] = 0.0
    image_data[50:71,50:71,2] = 0.0

    bonus_data = image_data[:,:,0] + image_data[:,:,1] + image_data[:,:,2]

    tev.create_image("Test Image", width=100, height=100, channel_names=["R","G","B","Bonus"])
    tev.update_image("Test Image", "R", image_data[:,:,0])
    tev.update_image("Test Image", "G", image_data[:,:,1])
    tev.update_image("Test Image", "B", image_data[:,:,2])
    tev.update_image("Test Image", "Bonus", bonus_data)

# At some later time...
with TevIpc() as tev:
    tev.close_image("Test Image")
```

![image](https://user-images.githubusercontent.com/10374559/111780435-b14df100-88b7-11eb-92a7-70ddf1db9ced.png)

Wrapper code:
```python
import socket
import struct
import numpy as np

class TevIpc:

    def __init__(self, hostname = "localhost", port = 14158):
        self._hostname = hostname
        self._port = port
        self._socket = None

    def __enter__(self):
        if self._socket is not None:
            raise Exception("Communication already started")
        self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) # SOCK_STREAM means a TCP socket
        self._socket.__enter__()
        self._socket.connect((self._hostname, self._port))
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        if self._socket is None:
            raise Exception("Communication was not started")
        self._socket.__exit__(exc_type, exc_val, exc_tb)

    def create_image(self, name: str, *, grab_focus = True, width: int, height: int, channel_names):
        if self._socket is None:
            raise Exception("Communication was not started")

        data_bytes = bytearray()
        data_bytes.extend(struct.pack("<I", 0)) # reserved for length
        data_bytes.extend(struct.pack("<b", 4)) # create image
        data_bytes.extend(struct.pack("<b", grab_focus)) # grab focus
        data_bytes.extend(bytes(name, "ascii")) # image name
        data_bytes.extend(struct.pack("<b", 0)) # string terminator
        data_bytes.extend(struct.pack("<i", width)) # width
        data_bytes.extend(struct.pack("<i", height)) # height
        data_bytes.extend(struct.pack("<i", len(channel_names))) # number of channels
        for cname in channel_names:
            data_bytes.extend(bytes(cname, "ascii")) # channel name
            data_bytes.extend(struct.pack("<b", 0)) # string terminator
        data_bytes[0:4] = struct.pack("<I", len(data_bytes))

        self._socket.sendall(data_bytes)

    def close_image(self, name: str):
        if self._socket is None:
            raise Exception("Communication was not started")

        data_bytes = bytearray()
        data_bytes.extend(struct.pack("<I", 0)) # reserved for length
        data_bytes.extend(struct.pack("<b", 2)) # close image
        data_bytes.extend(bytes(name, "ascii")) # image name
        data_bytes.extend(struct.pack("<b", 0)) # string terminator
        data_bytes[0:4] = struct.pack("<I", len(data_bytes))

        self._socket.sendall(data_bytes)

    def update_image(self, name: str, channel_name: str, image_data, *, grab_focus = False, x = 0, y = 0):
        if self._socket is None:
            raise Exception("Communication was not started")

        image = np.full(image_data.shape, 0.0, dtype="<f")
        image[:,:] = image_data

        data_bytes = bytearray()
        data_bytes.extend(struct.pack("<I", 0)) # reserved for length
        data_bytes.extend(struct.pack("<b", 3)) # update image
        data_bytes.extend(struct.pack("<b", grab_focus)) # grab focus
        data_bytes.extend(bytes(name, "ascii")) # image name
        data_bytes.extend(struct.pack("<b", 0)) # string terminator
        data_bytes.extend(bytes(channel_name, "ascii")) # channel name
        data_bytes.extend(struct.pack("<b", 0)) # string terminator
        data_bytes.extend(struct.pack("<i", x)) # x
        data_bytes.extend(struct.pack("<i", y)) # y
        data_bytes.extend(struct.pack("<i", image.shape[1])) # width
        data_bytes.extend(struct.pack("<i", image.shape[0])) # height
        data_bytes.extend(image.tobytes()) # data
        data_bytes[0:4] = struct.pack("<I", len(data_bytes))

        self._socket.sendall(data_bytes)
```

**Comment by Tom94** [comment]
That's amazing, actually!

Would you mind if I include your code in tev's repo (with minor modification to allow multi-channel updates & proper attribution, of course)? I'm thinking of providing it as a sample of how to interface with IPC.

**Comment by tomasiser** [comment]
@Tom94, please feel free to add the source codes directly to tev under the tev BSD licence. I was happy to help! :) Just keep in mind that the current IPC protocol may depend on the compiler and platform with which tev was compiled (e.g., little or big endian), in which case my Python code might not work.

**Comment by arpit15** [comment]
@tomasiser Is their a limit to the image size using the above python script? When I try to use the code for sending images of size greater than `600x600x3` I get following error

```
Traceback (most recent call last):
  File "sendImage.py", line 44, in <module>
    tev.update_image(base, "R", image_data[:,:,0])
  File "/home/arpita1/projects/tev/python-ipc/TevIpc.py", line 83, in update_image
    self._socket.sendall(data_bytes)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by tomasiser** [comment]
@arpit15 I think I used it with `1616x1240x1`, which should be more bytes than `600x600x3`. 🤔

**Comment by Tom94** [comment]
@arpit15 the latest version of tev adds two things that hopefully address the problem you're seeing:

1. tev is much more efficient with handling incoming image data, and
2. it comes with an updated version of Tomas' script that sends your image in tiles rather than one huge chunk.

I'd be curious to hear if there is still some left-over breakage on your end!
