### ISSUE TITLE
Multipart EXR Image Loading

### ISSUE THREAD

**Issue by MKimiSH** [Tom94/tev#133]
Currently tev does not support loading multipart EXRs. When such an image is loaded, only one part will be shown, which is the first part containing a layer that matches the provided layer selector. 

Recently I have managed to let tev load multipart EXRs more correctly by showing all layers that match the selector. It's not a big change, so before creating a PR I would like to know whether there is a reason behind this seemingly buggy behavior. 

Thanks! 
Xianyao

**Comment by Tom94** [comment]
The problem with multipart EXR files is that each part is _independent_ from the others, meaning they can have different resolutions, viewpoints, etc.. From the docs:
> Multipart: ability to encode separate, but related, images in one file.

This is semantically quite different from loading many channels that all describe the _same_ image. Plus, having different resolutions per channel is in conflict with some of the core mechanics in tev.

That said, I think there's still value in automatically loading all matched layers as long as their resolution is the same -- multipart files allow trading compression for loading speed after all.

My suggestion would be to only load those parts whose resolution equals that of the _first_ matched part, whereas all matched parts with non-equal resolutions should emit a warning (`tlog::warning() << stuff;`) to avoid confused users.

**Comment by Tom94** [comment]
Another aspect that I am not sure how to best handle is: what if different parts contain channels with the same names?

Can always append something to the duplicate channel names to disambiguate them, but this appendage should be something that's guaranteed to not clash with any other existing channel name.

**Comment by MKimiSH** [comment]
Hi Thomas,

Thanks for the replies. I think these are valid concerns that need to be properly considered for this feature. What I implemented was based on much stricter assumptions and I should probably keep it in house for now.
