### ISSUE TITLE
Moving tev between monitors causes scale factor problems

### ISSUE THREAD

**Issue by hjmallon** [Tom94/tev#135]
I built tev from master branch (for macOS HDR features! - thank you). I notice that if I open tev.app on an external display, then move it to the macbook pro display (or vice versa) I end up with scaling problems in the UI. The hitboxes for the mouse do seem to be correctly scaled, just not the image (making it extra difficult to use as they don't line up).

This screenshot is what happens if I move the app from the laptop display to an external display (extra small text etc). The opposite (extra big text) happens if I go the other way.

![Screenshot 2021-09-06 at 15 37 16](https://user-images.githubusercontent.com/1816667/132233278-5b6a4c6c-7b84-4802-a508-33b0dce3a867.png)

I built from dafebdbaf8ad8df8aa7c23219216c541e1f2025c

**Comment by Tom94** [comment]
Thanks for letting me know!

At first glance, this seems to be unsupported by tev's underlying GUI framework, nanogui; see
https://github.com/wjakob/nanogui/issues/448

However, there appear to be [at least some measures](https://github.com/wjakob/nanogui/blob/e9ec8a1a9861cf578d9c6e85a6420080aa715c03/src/screen.cpp#L426) in place for OSX specifically.

Will get back to this issue when I had a chance to investigate further.

**Comment by Tom94** [comment]
The fix appears surprisingly simple -- since I don't have a macOS dual-screen system with varying scales handy, would it be possible for you to test the linked branch?

**Comment by hjmallon** [comment]
That `content-scale` branch seems to work pretty smoothly for me, thanks for the speedy fix.
