### ISSUE TITLE
How the displayed value is calculated?

### ISSUE THREAD

**Issue by LogWell** [Tom94/tev#149]
I want to analyze an image numerically. The displayed result is different from the output of OpenCV/[cvkit](https://github.com/roboception/cvkit). 

Take the first-pixel(top-left) value, when check in [cvkit](https://github.com/roboception/cvkit) with: `sv ORTHO_ColorN_01_Z000_PRO.png`, and point to the top-left, the result is (126, 131, 254) and is consistent with the first `print()`. After gammaCorrection and divided by 255, the value is (0.21176471, 0.22745098, 0.98823529), but the displaied value is (0.2086, 0.2270, 0.9911). 

Since the image is a normal maps(or in other formats such as depth maps), the accuracy of the values is critical. 
So we hope `tev` can add the ability to [display raw value](https://github.com/Tom94/tev/issues/80).

CODE:
```
import cv2
import numpy as np


def gammaCorrectionDecoding(src, gamma):
    """
    NOTE: https://stackoverflow.com/a/16521337/10636347
        Gamma decoding is used to restore the original values, so the formula for that is:
        original = ((encoded / 255) ^ gamma) * 255
    """
    table = [((i / 255) ** gamma) * 255 for i in range(256)]
    table = np.array(table, np.uint8)
    return cv2.LUT(src, table)


path_img = "/home/lab9/Videos/for_tev/ORTHO_ColorN_01_Z000_PRO.png"
img = cv2.imread(path_img, -1)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = img[1082:1084, 990:993]
print(img)
img = gammaCorrectionDecoding(img, 2.2)
img = img / 255.0
print(img)
```

RES:
```
>>> [[[126 131 254]
  [127 131 254]
  [128 131 254]]

 [[123 126 254]
  [123 127 254]
  [122 127 254]]]

>>> [[[0.21176471 0.22745098 0.98823529]
  [0.21568627 0.22745098 0.98823529]
  [0.21568627 0.22745098 0.98823529]]

 [[0.2        0.21176471 0.98823529]
  [0.2        0.21568627 0.98823529]
  [0.19607843 0.21568627 0.98823529]]]
```

![ORTHO_ColorN_01_Z000_PRO](https://user-images.githubusercontent.com/34391447/145969493-c1acbf04-dd1d-4cde-8b1f-c7c11ad93f91.png)
![tmp](https://user-images.githubusercontent.com/34391447/145969735-c08c9218-3c98-451f-8720-68003c7e98bc.png)

**Comment by Tom94** [comment]
Hi there, the displayed value is `srgbToLinear(c / 255)`, where `srgbToLinear` is the standardized sRGB transform. Image from Wikipedia:
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/1cedac5578c8ba045e7ed1f4a4c5f760adcb7722)

If your PNG has an alpha channel `a`, then the complete formula is `srgbToLinear(c / 255) * a / 255`. Note that the alpha multiplication happens _after_ the conversion to linear colors. (This is defined in the PNG specification.)

Cheers!
