### ISSUE TITLE
tev (since 1.18) randomly crashes when opening new images on Windows

### ISSUE THREAD

**Issue by tomasiser** [Tom94/tev#157]
Hi there,

I am sorry for not having more details yet, but I've been noticing this problem for quite some time, likely since version 1.18, but the problem also persists in 1.20.

Sometimes, when I open new images to an existing tev instance (either from command line or via drag & drop), tev opens them but then crashes.

Last messages in console are related to STBI successfully loading the images, e.g.:
```
SUCCESS  Loaded 'blablabla.hdr' via STBI after 0.040 seconds.
```

There is **no error message in console**, except for occasional GLFW errors, but these occur frequently even without crashes.

```
GLFW error 65544: WGL: Failed to make context current: The requested transformation operation is not supported.
GLFW error 65544: WGL: Failed to make context current: The handle is invalid.
```

Windows event viewer also does not give any extra information, only states:

```
Faulting application name: tev (3).exe, version: 0.0.0.0, time stamp: 0x61c89d41
Faulting module name: ntdll.dll, version: 10.0.22000.348, time stamp: 0x22eb3761
Exception code: 0xc0000374
Fault offset: 0x000000000010be99
Faulting process ID: 0x69c4
Faulting application start time: 0x01d7fbf82a59c177
Faulting application path: C:\Users\tomas\Downloads\tev (3).exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 6ff0fc3e-a156-46d0-a2cf-be0d31331fca
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 1771698627124053311, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0
```

```
Fault bucket 2275847630276242728, type 5
Event Name: FaultTolerantHeap
Response: Not available
Cab Id: 0
```

Which I believe is completely worthless information.

I assume debugging this will need using tev in a debug mode with debug symbols, which I may have a look into at some point.

Anyone else experiencing this problem?

**Comment by tomasiser** [comment]
Uhm, it says exit code `3221226356`, googling this indeed points at this probably being a heap corruption problem, but that can easily be caused by something unrelated

**Comment by Tom94** [comment]
Hi Tomáš, does this by any chance get addressed by https://github.com/Tom94/tev/pull/156? I fixed a related-sounding heap corruption bug along the way, there. (Something to do with double-freeing certain coroutines.)

**Comment by Tom94** [comment]
Quick update: I think I managed to reproduce and fix the problem, but please feel free to re-open the issue if it comes back.
