### ISSUE TITLE
tev won't open EXR's from V-Ray

### ISSUE THREAD

**Issue by fursund** [Tom94/tev#168]
tev used to be able to open EXRs produced by V-Ray, but now fails with:
"13:23:46 ERROR    Could not load "test0.exr". Images with no channels should never exist."
[test0.exr.zip](https://github.com/Tom94/tev/files/7854506/test0.exr.zip)

**Comment by Tom94** [comment]
Oh wow, VRay prefixes all its channels with a ".", causing the root layer to be the empty string and causing ambiguity with regular root-level channels. I hadn't considered this case. Should be fixed now! (A hotfix binary release is to be pushed in the coming days.)
