### ISSUE TITLE
[MacbookPro M1] Image Flicker with Mouse Interaction

### ISSUE THREAD

**Issue by ommaury** [Tom94/tev#177]
Hi Thomas,

I'm experiencing a slight flickering any time I move the mouse over the UI (image or controls) or interact with the app. This is only happening on the mac, I haven't seen this behavior on windows.

TEV Release 1.23
MacbookPro M1

Hope this help,
Olivier

**Comment by Tom94** [comment]
Hi Olivier, this is already being tracked on the __nanogui__ end here: https://github.com/mitsuba-renderer/nanogui/issues/102

Cheers!

**Comment by ommaury** [comment]
Thanks Thomas for the quick response!

**Comment by Tom94** [comment]
Fixed by https://github.com/mitsuba-renderer/nanogui/issues/102#issuecomment-1287312558
