### ISSUE TITLE
Misleading documentation of UpdateImage in python lib.

### ISSUE THREAD

**Issue by Tomas-kubicek** [Tom94/tev#184]
HI, the comment
"""
        Updates the pixel values of a specified image region and a specified set of channels.
        The `image` parameter must be laid out in row-major format, i.e. from most to least
        significant: [col][row][channel], where the channel axis is optional.
"""
in the update funtion is wrong. Row major ordering is [row][col][channel]

**Comment by Tom94** [comment]
Good catch, thank you! Fixed on `master`.
