### ISSUE TITLE
Difference alpha/non-alpha images

### ISSUE THREAD

**Issue by beltegeuse** [Tom94/tev#198]
Hi Thomas,

I am not sure that the behavior is intentional, but the difference between the same OpenEXR image with and without an alpha channel does not work. Denying computing the difference between images with different numbers of channels is a very reasonable approach. 

However, by default, saving an OpenEXR image from tev automatically creates an alpha channel, which can break the difference computation when the image is reopened later. 

Is it possible to fix one of this behavior (saving or difference computation)? For example, I am unsure if fixing the OpenEXR saving can have a side effect. 

Best,
Adrien

**Comment by Tom94** [comment]
Hi Adrien, yeah, tev should be able to compare images with mismatched channels — it used to be supported in a hacky way, which seems to have broken at some point in the past year.

Could you check the linked PR for whether it fixes your use case? Mismatched top-level channels should now gracefully compare.

Things will still not work if the mismatched channels are situated in mismatched layers, which I plan to address in a future PR.

**Comment by beltegeuse** [comment]
Hi Thomas,

Yes the changes works perfectly! Thanks for your rapid response. 

Best,
Adrien
