### ISSUE TITLE
[Discussion] Should "Closing all" respect the current filter?

### ISSUE THREAD

**Issue by diiigle** [Tom94/tev#204]
Say I have a bunch of images open and I only want to close some that match a certain pattern (eg. "*_closeme.exr").
Intuitively I'd filter those out with the filename filter ("Find"/regex functionality) and then hit `Ctrl+Shift+W`.

Right now this closes indeed **all** images, even those that are hidden. 

What's the community's opinion on this?

**Comment by Tom94** [comment]
I think this would be correct behavior in any case -- I made the change real quick.

I also added a shortcut (Esc) to reset the current find string (which was sorely missing :)). If anyone relied on the previous behavior, they can press Esc followed by Ctrl+Shift+W from now on.
