### ISSUE TITLE
Saving dialog on Windows

### ISSUE THREAD

**Issue by diiigle** [Tom94/tev#210]
I believe you recently [fixed](https://github.com/Tom94/nanogui-1/commit/65b3f99ae57e770094850a6c9f0c76379fb15841) the saving dialog on Windows to not fail, when no extension was provided. That used to be quite an annoyance. 

However I believe there was a regression with this:
When you do provide an extension in the filename other than the one selected in the dropdown you will end up with both.

Example:
I want to save `myimage.png`, open the file dialog, paste `myimage.png`, but the default output format `OpenEXR` is selected. When you click save, you get a file in EXR format with the name `myimage.png.exr`.

**Comment by Tom94** [comment]
Good catch! Should be fixed on latest master (please feel free to re-open the issue if it resurfaces).
