### ISSUE TITLE
Is sRGB transformation a tonemapping?

### ISSUE THREAD

**Issue by yifanlu0227** [Tom94/tev#211]
Hi Thomas! Thanks for your repo, and it is a really convenient hdr viewer. 

As a newcomer to computer graphics, I've been studying your code and it has raised a few fundamental questions for me. I would greatly appreciate any assistance you could provide.

In my knowledge, the [sRGB transformation](https://github.com/Tom94/tev/blob/00e9cc5ec2802976b460d30d566a591afba409af/src/ImageCanvas.cpp#L509C12-L509C12) is a standard gamma correction for linear color in sRGB space. And the tonemapping is performed before the gamma correction, like Reinhard tone mapping, Filmic tone mapping. 

You consider sRGB conversion as a tonemapping method, which makes me confused. I sincerely look forward to your help.

**Comment by Tom94** [comment]
Hi Yifan, you're right: the sRGB transformation is indeed a transfer function that plays a different role (compression before sending bits to the monitor) from tone mapping operators (usually to map HDR colors to LDR colors). I really like [this StackOverflow answer](https://computergraphics.stackexchange.com/questions/10315/tone-mapping-vs-gamma-correction) in answering the nitty gritty details, but based on your question you probably already got them down.

However, __tev__ doesn't really deal much with color spaces/gamuts and has a few visualization tone maps that _don't_ apply the transfer function (false-color and +/-)... which is admittedly a hacky way to make the visualized colors more perceptually uniform to a human (via the inverse of the transfer function that the monitor applies). So in the interest of not overcomplicating the code I just loosely refer to all of these operations as a single "tone mapping" step. If __tev__ ever were to get support for a wide variety of color spaces and tone mapping operators, refactoring would be due. :)

**Comment by yifanlu0227** [comment]
That makes sense! Thank you for your help!
