### ISSUE TITLE
Unexpected files occur in installation

### ISSUE THREAD

**Issue by comradez** [Tom94/tev#227]
After commit [eb40611](https://github.com/Tom94/tev/commit/eb40611503c9e5dcac4b72d3b49505bf0009f8e1) has changed OpenEXR and Imath repos to upstream, if you follow the CMake instructions given in the README and do 
```
cmake . -B build
```
Then during installation, the headers and compiled static libs of OpenEXR and Imath will also be installed, which is not expected and has affected [the AUR package](https://aur.archlinux.org/packages/tev).

One possible solution would be adding `-DOPENEXR_INSTALL=OFF -DOPENEXR_INSTALL_TOOLS=OFF -DOPENEXR_INSTALL_PKG_CONFIG=OFF -DIMATH_INSTALL=OFF -DIMATH_INSTALL_PKG_CONFIG=OFF`, explicitly disabling their installation on configuration, and updating this in the README might help avoid potential problems (like someone using `CMAKE_INSTALL_PREFIX=/usr` accidentally overwritten their OpenEXR headers).

**Comment by Tom94** [comment]
Ouch, apologies for missing this when upgrading the dependencies. Imath / OpenEXR installation should now be disabled on latest `master`. Thank for reporting!
