### ISSUE TITLE
Ctrl+number cannot select channel groups on Linux/Windows

### ISSUE THREAD

**Issue by MKimiSH** [Tom94/tev#229]
I believe the cause is the `!(modifiers & SYSTEM_COMMAND_MOD)` in the following line: https://github.com/Tom94/tev/blob/13352738362d65d1b89dea4b81d8756bb5cc1368/src/ImageViewer.cpp#L686. On Windows and Linux, this is the same as Ctrl, so it blocked the Ctrl+number key combination. This seems related with introducing Ctrl/Cmd+0 and Ctrl/Cmd+9 for setting image transforms. 

I think the new Ctrl+0/9 behavior is more useful than selecting the 9th or 10th channel group. Meanwhile, we can perhaps keep Ctrl+[1-8]? It introduces a bit of inconsistency though.

**Comment by Tom94** [comment]
Oops, good catch! Thanks & sorry for the accidental breakage. Just pushed a fix that makes Ctrl+1-8 work (I agree 9 and 0 aren't necessary here).
