### ISSUE TITLE
Missing blocks in .exr

### ISSUE THREAD

**Issue by roflmaostc** [Tom94/tev#239]
Hi,

another thing I discovered (starting to wonder if it's me 😛).

tev — The EXR Viewer
version 1.27dev (64 bit)
on
Linux nearth 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux

If I open [this picture](https://wolke.sumpi.org/index.php/s/dXCtRcome3ezRe5), I see some empty blocks. With GIMP it looks fine:

![Screenshot_2024-10-02_11-44-04](https://github.com/user-attachments/assets/f62ade7f-c659-4e13-8bba-bc7121b6c903)

Best,

Felix

**Comment by Tom94** [comment]
Hi, that's strange. That image loads correctly for me. Both on macOS (M1 max) and Linux (Ubuntu, NVIDIA RTX 4090, latest driver). I also never heard of anyone else having that particular problem with tev.

If you figure out what causes it (or find another hint), I'd be more than curious to hear about it!

**Comment by roflmaostc** [comment]
The funny thing is, I tried it again, now it works...

But I remember I had similar issue yesterday too.
I'll close for now. Thanks for your quick help :)
