### ISSUE TITLE
Mean bigger than max in histogram

### ISSUE THREAD

**Issue by sergio-sancho** [Tom94/tev#242]
Hi, I was importing an image and I realized that the mean value shown in the histogram can be bigger than the maximum. It seems that the mean is computed as the sum of all the values divided by pixelCount and not by (pixelCount * nChannels) while the min and max are over all values in all channels:

https://github.com/Tom94/tev/blob/1432175b87ab83ba686dfebb648fb4b0e4fd6c08/src/ImageCanvas.cpp#L911

I was wondering if this is intended. It feels a bit unintuitive to me. Thanks!

**Comment by Tom94** [comment]
Oh snap, my bad, looks like I introduced this bug recently. Thanks for reporting! Fixed on latest master and will push a hotfix release in a bit.
