### ISSUE TITLE
What are the icons for?

### ISSUE THREAD

**Issue by svenevs** [Tom94/tev#28]
With a `CMAKE_INSTALL_PREFIX=/opt/tev`, I get:

```
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/tev/bin/tev
-- Installing: /usr/share/applications/tev.desktop
-- Installing: /usr/share/icons/hicolor/512x512/apps/tev.png
-- Installing: /usr/share/icons/hicolor/256x256/apps/tev.png
-- Installing: /usr/share/icons/hicolor/128x128/apps/tev.png
-- Installing: /usr/share/icons/hicolor/96x96/apps/tev.png
-- Installing: /usr/share/icons/hicolor/64x64/apps/tev.png
-- Installing: /usr/share/icons/hicolor/48x48/apps/tev.png
-- Installing: /usr/share/icons/hicolor/32x32/apps/tev.png
-- Installing: /usr/share/icons/hicolor/24x24/apps/tev.png
-- Installing: /usr/share/icons/hicolor/16x16/apps/tev.png
```

What is the intended purpose of these images?

**Comment by Tom94** [comment]
Hi Stephen,

these icons are installed to the system-wide lookup folder for desktop environments implementing the [freedesktop standard](https://specifications.freedesktop.org/icon-theme-spec/latest/). I tested this and made sure it works correctly on Unity (Ubuntu), Gnome 3, and KDE Plasma 5.

Admittedly, the installation could be made a bit more customizable for non-freedesktop environments and for people who want to install tev only for the local user.

Cheers!

**Comment by svenevs** [comment]
Very sleek!  I'm not sure why, but I had to manually double click on the installed `.desktop` before it shows up in the launcher in Gnome 3.  I put the full path to `/opt/tev/bin/tev` as well.  Maybe if `CMAKE_INSTALL_PREFIX` is not `/usr/local` just put the full path?  I also had to manually specify the path to e.g. the 512x512 icon.  I don't know why I would have to do that, though, since other system icons such as the calendar are in that same folder and they work.

This is on Fedora 25 (GNOME Shell 3.22.3), but honestly I don't think it matters that much / isn't worth fixing.  Most people are happy to install to `/usr/local`.  I keep custom things in `/opt` so I can blow them away without thinking :)

I wish I knew about tev when I was working on rendering, the tool I was using was very finicky / the UI was really tedious to use (lots of click menu A then B then C).  Great work!!!

**Comment by Tom94** [comment]
I've found that most desktop environments take a while to update their caches to list the application and show the correct icon. Manually double clicking the `.desktop` might have accelerated that for you.

Putting the full path of the installed tev into the `.desktop` file sounds like a good idea in general. After all, the `.desktop` file should always work, even if tev is not in `PATH`. Unfortunately, using the full path for icons would be a bit problematic, since---as you noticed---it requires choosing one specific resolution. At this point I am hoping your icons did not work immediately because of another layer of caching.

Glad to hear you like tev! :)

**Comment by svenevs** [comment]
Right you are, the icon cache needs updating as well.  If anybody is reading this, online you may find people encouraging `sudo gtk-update-icon-cache`.  This was not sufficient for me, but making the `hicolor` sub-directory was!  It printed a message indicating success as well:

```console
$ sudo gtk-update-icon-cache /usr/share/icons/hicolor/
gtk-update-icon-cache: Cache file created successfully.
```

Thanks @Tom94
