### ISSUE TITLE
tev color mismatch issue

### ISSUE THREAD

**Issue by sus-unn** [Tom94/tev#49]
Color space mismatch in tev
===============

![image](https://user-images.githubusercontent.com/36620824/40852232-bd622638-6604-11e8-9179-a4d73605d49b.png)

When I render in blender, and open the result image(exr) in tev, color looks different from blender.

In the left, tev and windows image viewer(jpg converted from exr). In the right, blender render result viewer.

You can see the reflections of the ball in the right clipped in tev and windows image viewer.

It looks just like in windows image viewer, so I think this is problem related to icc profile or something.

I'm not color professional, so I don't know what's behind this but there clearly is a color mismatch anyway.

I am currently using win10, blender 2.79b. tev version is 1.9.

**Comment by Tom94** [comment]
Hi there,

thanks for reporting this issue! Do you by any chance know what kind of tonemapping algorithm blender is using? Please make sure it uses the [sRGB](https://en.wikipedia.org/wiki/SRGB) transformation to match __tev__ out-of-the-box. Alternatively, use Gamma and configure __tev__ to do so as well (there is a button near the top-left).

In case you are not familiar with tonemapping: High dynamic range images (such as stored in EXR files) can not directly be displayed but need to first be converted to low dynamic range before being sent to the graphics card. This conversion is called "tonemapping" and there exist various popular ways of doing so. Using different tonemapping algorithms leads to different appearances. My suspicion is that blender simply uses a different tonemapping algorithm than __tev__ does. __tev__ uses the [sRGB](https://en.wikipedia.org/wiki/SRGB) transformation by default.

Cheers!

**Comment by sus-unn** [comment]
Ahh.., I used filmic, and in my knowledge, it should map scene referred data to sRGB transformation. 
To figure out I opened the rendered .exr image in DaVinci Resolve and changed LUT of the clip.. And to match the look in blender's render result view, it was not sRGB I belive. It was something else.
I don't remember what it was so I will tell you later.

**Comment by Tom94** [comment]
Filmic tonemapping operators (there exist a bunch of different ones) involve more than just a simple sRGB transformation, so this explains the discrepancy. Since this is not an issue of tev I'll be closing this issue.

I am not opposed to an implementation of popular tonemapping operators within tev to get appearance to match in case somebody wishes to implement some.

Thanks again for the info! :)
