### ISSUE TITLE
Loading all images from a folder

### ISSUE THREAD

**Issue by ghost** [Tom94/tev#50]
Hello,
Thank you so much for creating this repo. 

What do I have to do in order to:

1. Load 1000 image names from a folder, populate your LHS image list with these names and then trigger image display upon clicking an image name on the list  

2. Following that, I want to display the image and the normalized image side by side in the image pane

Thanks,

**Comment by Tom94** [comment]
Hi there,

unless I misunderstand something, 1. should be easy to do. Via the command line, add tev to your `PATH`, then do `tev path/to/folder/*`. If you prefer using a file browser (e.g. explorer on Windows), make `tev` your default application for opening the type of image file you are using, then select all images in the given folder via `Ctrl+A`, and then press Enter. (Cmd+A; Cmd+Down on macOS.)

Your second use case is unfortunately not supported by tev. tev can only display a single image at a time.

Cheers!

**Comment by QuantScientist** [comment]
Hi Tom!
Thanks for the prompt reply :) 
I meant amending the code and the nanoGUI components directly and not via the command line (though its is nice that it is possible).

Something like this QT example: 

![687474703a2f2f7777772e7669616d65746f6f6c6b69742e6f72672f77702d636f6e74656e742f75706c6f6164732f323031372f30332f696d6167655f706c617965722e706e67](https://user-images.githubusercontent.com/18743986/41776833-e35b1664-7631-11e8-956a-459722f1e924.png)

**Comment by Tom94** [comment]
Oh, I see! I think the easiest route would be to create 2 `ImageCanvas` widgets side-by-side (instead of having a single one like right now) and have `ImageViewer` set the image and display settings of both accordingly.

A slightly more direct (and hacky) approach would be to bake the normalized image and the original image into a larger image (with twice the width) within the respective image loading routines in `Image.cpp`.

Hope this helps! :)

**Comment by QuantScientist** [comment]
Yes, it does. Thanks. 
Any idea why loading a single JPG would take so long on a very strong computer? 

![2018-06-22 16_13_52-c__windows_system32_cmd exe - tev exe](https://user-images.githubusercontent.com/18743986/41778592-d2113644-7637-11e8-8662-51407d05f723.png)

Also, more than 3/4 of my images fail to load with this error:
![2018-06-22 16_13_04-c__windows_system32_cmd exe - tev exe](https://user-images.githubusercontent.com/18743986/41778603-dca0d268-7637-11e8-916e-ce234b162751.png)

Do I need to covert some of them to another format? 
Many thanks!

**Comment by QuantScientist** [comment]
Also, if I select 50 images (CTRL A), and the selct an Image it allways ends like this:
![image](https://user-images.githubusercontent.com/18743986/41778762-65c84ed6-7638-11e8-9196-62d6577591c4.png)
