### ISSUE TITLE
Crash due to X error 20 (X_GetProperty) upon file opening under XMonad

### ISSUE THREAD

**Issue by mrossinek** [Tom94/tev#58]
I installed tev via the AUR and I can start it just fine. However, as soon as I try to open a file (or start with a file via the command line) I get the following error from tev crashing;
```
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  218
  Current serial number in output stream:  218
```

It is neither dependent on the file nor the file type (at least as far as I can tell).

I am using version 1.12dev under Arch Linux (4.18.10-arch1-1-ARCH) running xmonad version 0.14

**Comment by Tom94** [comment]
Hi Max, thanks a lot for reporting this! Unfortunately, I cannot say at which point I will find the time to set up a VM with XMonad to debug this issue.

However, I suspect that this is an underlying problem with GLFW, the library tev uses for interfacing with the window manager and OpenGL. Could you try running `tev --max=1` and see whether this causes the error without opening any images?

**Comment by mrossinek** [comment]
Hi Tom! Yeh I can understand that this would take a while to debug...

I tried your suggestion and everything runs fine. I suppose this just confirms your suspicion of this being a GLFW bug, right? Shall I go ahead and report it there as well?
During my research yesterday I found this (https://github.com/glfw/glfw/issues/789) but this is a different X Error. I also asked for a quick tip in their irc channel on freenode but to no avail.

**Comment by Tom94** [comment]
Actually, `tev --max=1` not producing any errors doesn't really shed much light. I was hoping it would immediately error out. This rules out the maximize call to X producing the error you experience.

That said, the issue you linked sounds like it might be the actual problem: tev uses GLFW to set focus upon loading an image, so it'd be plausible if `XSetInputFocus` was the culprit. Could you show me the full console output of tev when crashing? If the error is caught in the form of an exception, then I could simply make focus operations fail gracefully rather than hard-crashing the program.

**Comment by mrossinek** [comment]
Okay, here is the console output of tev when trying to open it with an EXR file from the console;
```
11:31:57 INFO     Loading window...
11:31:57 SUCCESS  Loaded '/path/to/file.exr' via OpenEXR after 0.013 seconds.
X Error of failed request:  BadAtom (invalid Atom parameter) 
  Major opcode of failed request:  20 (X_GetProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  218
  Current serial number in output stream:  218
```
When starting tev first and then trying to open a file results in the exact same output except for the serial number changing to `838`.

Is there a debug argument to run tev with? Because this is not more information than I could give in the very beginning. Using `tev -h` I don't see a debug or verbose option..

**Comment by Tom94** [comment]
Thank you very much for looking further into this!

This unfortunately looks like there is no exception being thrown and caught anywhere. :(
No, there is no option to make the output of tev more verbose, but I also don't think it'd help much in this case.

If you are willing to compile tev by yourself, please try commenting out all 4 `glfwFocusWindow` calls in `ImageViewer.cpp`. I suspect this will fix the problem for you, and if it does, it points us to a fundamental problem in GLFW.

**Comment by mrossinek** [comment]
Okay I tried that but to no avail.. The error message did not change at all
Unfortunately, I don't have the time right now to dig deeper into this.

If you have another idea what I could try I am open to it.

**Comment by Tom94** [comment]
Nothing immediate comes to my mind. Thank you very much for your time; I'll see if I can find out more by getting XMonad myself once I find some time.

**Comment by mrossinek** [comment]
Sure, no prob!
If I can help any further, let me know! I should be able to find some time here and there for testing if that would help

**Comment by Tom94** [comment]
Cleaning up old issues: if this is still an active problem, feel free to re-open :)

**Comment by kai0200** [comment]
try

yay -S gnome-settings-daemon

/usr/lib/gsd-xsettings &

**Comment by Neburski** [comment]
I was experiencing the same as in the first post for this issue.

Since recently (I can't say what fixed it though), this issue has disappeared, I can open EXR, JPG, PNG, (most likely others as well, but not tested).

I merely wanted to report that the issue has been resolved.
