### ISSUE TITLE
channels, when specified, are reordered

### ISSUE THREAD

**Issue by mmp** [Tom94/tev#68]
I have an EXR image that has (among other things) channels named "LeR", "LeG", "LeB" (emitted radiance, RGB). If I run `tev :LeR,LeG,LeB out.exr`, then the image is displayed with red for "LeB", green for "LeG", and blue for "LeR" (i.e., the blue and red channels are swapped).

This seems to be happening because `Image::readExr()` loops over the channels in the EXR file in order and takes the ones that match the channel selector in the order that they're found. (I'm not sure what the appropriate fix is, though, or if there's already a way to get the behavior I'm hoping for.)

I can provide a test case if that's helpful.

**Comment by Tom94** [comment]
Hi Matt, to get the desired behavior right now, you could bundle emitted radiance into its own layer (i.e. Le.R, Le.G, Le.B). There is a hard-coded heuristic to automatically order channels that are known to belong together, such as r, g, b.

As for the appropriate fix, I suppose a sorting step within `readExr()` would be simple enough to add. Also, the aforementioned heuristic could be smarter (e.g. matching *R,*G,*B with common prefix). I'll make sure to add these things once I get the chance. :)

**Comment by mmp** [comment]
Hi, Thomas--Ah, I didn't know about layers in EXR--that's easy enough for me to do when I generate the EXRs and indeed, with that, the channels come out in the desired order. Thanks!
