### ISSUE TITLE
tev-32bit.exe malware false-positive?

### ISSUE THREAD

**Issue by jammm** [Tom94/tev#76]
Windows 10 smart screen blocks me from running both tev.exe and tev-32bit.exe.

Virustotal didn't show any viruses - https://www.virustotal.com/gui/file/24dc913955feb9eb9d5685eb4115f75db7cce9559b60e81b0e1695cb2f3814fa/detection

32bit does show some weird malware though:
https://www.virustotal.com/gui/file/ad4f92ae91d43fc440258c4aad709032bbf33130337a4bc15fe5b9b6aaa28b6d/detection

Could it be a false positive?

**Comment by Tom94** [comment]
Windows doesn't like it when you execute unsigned binaries. As I am not signing the releases, there's a good chance you're running into that particular problem. (And no, I didn't put any Malware into tev. :P)

If you don't want to manually override smart screen (there should be a button somewhere), your best bet is to inspect and compile the source code yourself.

**Comment by jammm** [comment]
No worries ! I had actually ran tev before making the issue. I knew it was a false positive. My intention was to put this issue up in case anyone else is wondering.

**Comment by Tom94** [comment]
Since there's no longer a 32bit executable bundled with the releases, I'm gonna go ahead and close.
