### ISSUE TITLE
Display of pixel values text for single-channel images with alpha channel

### ISSUE THREAD

**Issue by dvicini** [Tom94/tev#78]
Hi, 

It seems that the display of the pixel values as text behaves in a surprising way for EXR images with only a luminance and an alpha channel:
![image](https://user-images.githubusercontent.com/5487532/66939532-12550380-eff8-11e9-8cf7-b159b4e4dddd.png)

The luminance value is displayed twice, whereas the alpha channel values are not displayed. The compositing of the image is correct, just the text output is confusing. For RGBA images, everything works as expected and I get text labels for R,G,B and A.

Delio

**Comment by Tom94** [comment]
Whoops; this is what happens when you take hacky shortcuts. :)

Thanks for reporting!
