### ISSUE TITLE
display raw RGB values

### ISSUE THREAD

**Issue by ajtao** [Tom94/tev#80]
Tev currently displays floating point color values in the top border of the window.
Would it be possible to also display the raw color values as well? So for png, jpg, it would show RGB(A) as 8b integers. There are many uses of this, but for example, i was recently looking at a semantic segmentation dataset, and i wanted to know the exact value at a pixel because the image was encoding the class label ID there.

**Comment by Tom94** [comment]
Implemented. :)

The values are now displayed in hecadecimal 0xRRGGBBAA format within the title bar as well as each individual pixel when zoomed in and ALT is held.

**Comment by LogWell** [comment]
But this format is not easy to read, how can I display the general decimal value?

**Comment by Tom94** [comment]
Displaying the decimal LDR value is currently not supported. It's also not planned (as of now) to be added, given the focus of tev to be an HDR image viewer.

**Comment by LogWell** [comment]
`tev` is very comfortable to use, but we often need to check decimal values, we may need to resort to other viewers such as `cvkit`. So there are some regrets. 

Anyway, thank you very much~
