### ISSUE TITLE
Closing the app with ESC is annoying

### ISSUE THREAD

**Issue by luksladky** [Tom94/tev#84]
It might my personal issue, but I keep closing tev by accident all the time. Am I the only one?

**Comment by Wagyx** [comment]
No, you are not, it happened to me a few times at first too. I don't do it anymore though. Maybe a different input like Ctrl+Q would be good instead.

**Comment by MKimiSH** [comment]
I think Q alone quits tev as well. Esc is probably the default with NanoGUI?

**Comment by Tom94** [comment]
I'm torn on this one -- and been putting it off far too long. :)

Could any reader of this comment vote for/against closing via Esc using thumbsup/thumbsdown reactions? I'll do what the majority decides.

**Comment by MKimiSH** [comment]
1. Why do we allow two keys for quitting tev? It will make sense to close with Esc if Q is assigned another task. 
2. If it's not too difficult, maybe it's better to have a confirmation pop-up after pressing Esc or Q which now directly quits tev. This will force a two-key (or more) sequence, like Esc-Enter or Q-Enter, and reduce the possibility of accidents.

**Comment by Tom94** [comment]
> 1. Why do we allow two keys for quitting tev? It will make sense to close with Esc if Q is assigned another task.

I personally don't feel strongly about Esc, except for a slight leaning towards keeping it to not break anyone's workflow. Hence the vote. From the current state of it, it looks like I'll end up removing the shortcut with the next release. :)

>     2. If it's not too difficult, maybe it's better to have a confirmation pop-up after pressing Esc or Q which now directly quits tev. This will force a two-key (or more) sequence, like Esc-Enter or Q-Enter, and reduce the possibility of accidents.

The point of the Q shortcut is to have an easily accessible (left hand; no finger gymnastics) and quick way to close the program. A confirmation dialog would directly directly counter that.

That said, Ctrl/Cmd+Q sounds like a good way forward to me
- on macOS, Cmd+Q already does the job, so __tev__ become more aligned with the OS.
- Windows' Alt+F4 requires finger gymnastics, but Ctrl+Q doesn't
- Linux desktop shortcuts aren't really standardized to my knowledge, but some to have Ctrl+Q

**Comment by MKimiSH** [comment]
I see your points. Ctrl/Cmd+Q sounds much nicer than an additional dialog.
