### ISSUE TITLE
View multiple channels in layer

### ISSUE THREAD

**Issue by Wagyx** [Tom94/tev#92]
Hello Tom94,

Thank you for the software, it is amazing.

Here is my issue. I have an image with RGB channels as well as XYZ ones.
They are all listed as part of the <root> layer when the mouse hovers above the image name on the left panel. I guess the color image I see on the main window is only the display of the RGB channels as it should but what about the XYZ channels ? I can't even view their values when zooming in nor switch between layers since there is only the <root> one.

I know I could make a new layer for the XYZ channels but I propose two additional features.
The first would be to display all the values of the channels of the current layer when zooming in instead of only the first three (or RGB). The downside is that the display would could become quite hectic when there is more than 6-7 channels.

The second would be to have a way to switch between channels like the way we can switch between layers (this feature is already so useful).
Or a way to select the channels we want to display.

What do you (and other people) think ?

**Comment by Tom94** [comment]
Hi there,

I'm happy to make the titlebar and the zoomed-in view display all channels. This is a great suggestion! (See the above PR.)

But I am unsure about how to best approach switching between channels of the same layer. I don't want to make the interface unnecessarily complex and I believe layers _already_ provide a good mechanism to subdivide the image into individually useful chunks.

As a workaround, for now, you can open specific channels via the `:channel1,channel2,...` notation. In your case, you can view just the XYZ channels via `tev :X,Y,Z image.exr`.

**Comment by Wagyx** [comment]
Thank you for the answer.
Keeping the Left/Right arrow keys for the layer is necessary.
I propose to use Shift+ Left/Right arrow keys to switch between channels in the selected layer.
I know they are used to switch between tonemaps but it is redundant with the Shift+A/D, don't you think ?
Also, you will need to show somewhere which channel is currently displayed.

**Comment by Tom94** [comment]
The redundancy between W/A/S/D and Up/Left/Down/Right is intentional to permit full right- and left-handed usage. Likewise, it's non-obvious to me how to best approach a good (and general!) UI for doing this.

So far, I'm strongly leaning towards a "won't fix" approach with the reasoning, that users should simply make more layers.

Out of curiosity: what is the reason you can't just make different layers for your use case?

**Comment by Wagyx** [comment]
I understand.

The reasons are simple, I did not make the pictures and I have hundreds or thousands of them in many different locations across my computer.
I also have spectral images with all the wavelength channels (tens or hundreds) in the same layer.

**Comment by Tom94** [comment]
I see, so if there was a way to easily convert these EXR files to have a layer separation, your problem would be solved?

I can imagine giving tev a command-line option to break duplicate channel groups within single layers into individual layers.

**Comment by Tom94** [comment]
Hi @Wagyx , thinking some more about your use case made me change my mind about introducing this functionality. In particular spectral images are a very valid case of many channels within a single layer.

Does the referenced PR work for you?

**Comment by Wagyx** [comment]
Hi Tom94,
thank you for reconsidering the matter.
The PR probably works, I could compile the master on Windows but when running the exe, it fails silently.

**Comment by Tom94** [comment]
Try the released binary at https://github.com/Tom94/tev/releases/tag/v1.15

**Comment by Wagyx** [comment]
Yes, it works. Many thanks to you.
